// 캘린더 자동수집 데이터 — fetch_calendar.py 생성 (공개, 평문)
window.CALENDAR_AUTO = {
  "as_of": "2026-07-06",
  "note": "원문 공식 소스 자동수집(BLS·yfinance·관세청). 컨센/ISM/DRAM은 무료 API 없음 → 큐레이션 오버레이.",
  "sources": [
    "BLS 5건",
    "어닝 0건"
  ],
  "events": [
    {
      "date": "2026-06-13",
      "type": "macro",
      "region": "US",
      "title": "🇺🇸 미 CPI (헤드라인)",
      "unit": "% YoY",
      "source": "BLS",
      "importance": 3,
      "consensus": null,
      "prior": null,
      "actual": "4.2%",
      "mom": "0.5%",
      "yoy": "4.2%",
      "released": true,
      "verified": true,
      "autokey": "us_cpi",
      "auto": true,
      "ref_period": "2026-05",
      "url": "https://www.bls.gov/cpi/",
      "detail": "CPI-U 지수 335.123 (NSA, May 2026). SA MoM 0.5%.",
      "interp": "자동 수집(원문 공식 소스). 컨센서스·해석은 큐레이션 오버레이 참조."
    },
    {
      "date": "2026-06-13",
      "type": "macro",
      "region": "US",
      "title": "🇺🇸 미 근원 CPI",
      "unit": "% YoY",
      "source": "BLS",
      "importance": 3,
      "consensus": null,
      "prior": null,
      "actual": "2.9%",
      "mom": "0.2%",
      "yoy": "2.9%",
      "released": true,
      "verified": true,
      "autokey": "us_core_cpi",
      "auto": true,
      "ref_period": "2026-05",
      "url": "https://www.bls.gov/cpi/",
      "detail": "근원(식품·에너지 제외) May 2026. SA MoM 0.2%.",
      "interp": "자동 수집(원문 공식 소스). 컨센서스·해석은 큐레이션 오버레이 참조."
    },
    {
      "date": "2026-07-03",
      "type": "macro",
      "region": "US",
      "title": "🇺🇸 미 실업률",
      "unit": "%",
      "source": "BLS",
      "importance": 3,
      "consensus": null,
      "prior": "4.3%",
      "actual": "4.2%",
      "mom": null,
      "yoy": null,
      "released": true,
      "verified": true,
      "autokey": "us_unrate",
      "auto": true,
      "ref_period": "2026-06",
      "url": "https://www.bls.gov/ces/",
      "detail": "실업률 4.2% (June 2026, SA).",
      "interp": "자동 수집(원문 공식 소스). 컨센서스·해석은 큐레이션 오버레이 참조."
    },
    {
      "date": "2026-07-03",
      "type": "macro",
      "region": "US",
      "title": "🇺🇸 미 비농업고용(NFP)",
      "unit": "천명",
      "source": "BLS",
      "importance": 3,
      "consensus": null,
      "prior": "+129K",
      "actual": "+57K",
      "mom": null,
      "yoy": null,
      "released": true,
      "verified": true,
      "autokey": "us_nfp",
      "auto": true,
      "ref_period": "2026-06",
      "url": "https://www.bls.gov/ces/",
      "detail": "비농업 취업자 전월대비 +57천명 (June 2026, SA).",
      "interp": "자동 수집(원문 공식 소스). 컨센서스·해석은 큐레이션 오버레이 참조."
    },
    {
      "date": "2026-07-03",
      "type": "macro",
      "region": "US",
      "title": "🇺🇸 미 시간당임금(AHE)",
      "unit": "% YoY",
      "source": "BLS",
      "importance": 3,
      "consensus": null,
      "prior": null,
      "actual": "3.5%",
      "mom": "0.3%",
      "yoy": "3.5%",
      "released": true,
      "verified": true,
      "autokey": "us_ahe",
      "auto": true,
      "ref_period": "2026-06",
      "url": "https://www.bls.gov/ces/",
      "detail": "시간당 평균임금 $37.64 (SA). MoM 0.3% / YoY 3.5%.",
      "interp": "자동 수집(원문 공식 소스). 컨센서스·해석은 큐레이션 오버레이 참조."
    }
  ]
};
